### ISSUE TITLE
Unused variables should produce a warning

### ISSUE THREAD

**Issue by juanique** [clutchski/coffeelint#22]
Most Lint checkers (for other languages) have this feature, I find it to be very useful to catch typos (read http://stackoverflow.com/questions/9835697/is-there-a-way-to-catch-typos-when-writing-coffeescript for an example).

**Comment by joelbarker2011** [comment]
Not sure why this issue was closed; it is definitely (still) a problem.

**Comment by AsaAyers** [comment]
It's closed because it's not going to get implemented. See https://github.com/clutchski/coffeelint/issues/20#issuecomment-124888702

I also recommend reading my post: [You Don't Need CoffeeScript](https://gist.github.com/AsaAyers/d09e4de118b8d6b5e2d8fa3e38e496e0)

**Comment by anildigital** [comment]
:+1:
