### ISSUE TITLE
Bitwise

### ISSUE THREAD

**Issue by EvanHahn** [clutchski/coffeelint#265]
I like the `bitwise` operation from JSHint:

> This option prohibits the use of bitwise operators such as `^` (XOR), `|` (OR) and others. Bitwise operators are very rare in JavaScript programs and quite often `&` is simply a mistyped `&&`.

Would that be welcome in the core, or just as an external plugin?

**Comment by swang** [comment]
Doesn't seem like there has been much progress on this. And TBH I just don't see this (& mistaken for &&) happening in coffeescript enough to warrant this to be in core.
