### ISSUE TITLE
MissingFatArrow is triggered on constructor

### ISSUE THREAD

**Issue by volkhin** [clutchski/coffeelint#292]
As I understand constructor can't be declared with fat arrow (at least it doesn't work with browserify), but coffeelint with rule MissingFatArrow: warn requires it.

P.S. actually it was true in 1.1, maybe it's fixed now. grunt-coffeelint is so old :(
P.P.S not working in coffeelint 1.5.2 neither.

**Comment by swang** [comment]
This looks like it's been resolved since it was issued (the given code clears with missing_fat_arrows set to error) so I'm closing this. If this is an issue please reopen or resubmit a new issue.
