### ISSUE TITLE
add rule for unnecessary parentheses, e.g. if (err) return err;

### ISSUE THREAD

**Issue by kevinburkeshyp** [clutchski/coffeelint#380]

**Comment by AsaAyers** [comment]
There isn't enough info here

**Comment by kevinburkeshyp** [comment]
sorry - an example is

if (foo)
    doSomething()

Could be written as

if foo
    doSomething()

-kevin

On May 15, 2015, at 22:11, Asa Ayers <notifications@github.com> wrote:

Closed #380 <https://github.com/clutchski/coffeelint/issues/380>.

—
Reply to this email directly or view it on GitHub
<https://github.com/clutchski/coffeelint/issues/380#event-306349314>.

**Comment by AsaAyers** [comment]
ok, you're welcome to contribute a PR or publish your own rule. I just don't usually implement rules that I'm not going to use myself.

**Comment by jedcn** [comment]
Hi there, @kevinburkeshyp. You might be interested in this rule that I recently published: https://github.com/jedcn/coffeelint-prefer-poet-mode.

It's not what you've described, instead it's more about removing unnecessary parens around function invocation.

It's early going and my first rule, so I'm not quite sure how it'll turn out. But, it's been helpful to myself and a few friends.

I expect it to grow in the next few weeks as we run it against more real world CoffeeScript.
