### ISSUE TITLE
Unused variable detection

### ISSUE THREAD

**Issue by bazineta** [clutchski/coffeelint#386]
I'd like to be able to detect unused variables used for import purposes.  In this scenario, the variable is declared and assigned to, but is thereafter unused.

What I'm trying to detect is places where we've done a Foo = require 'foo', but then don't actually use Foo in the module.

I'd guess that this is plugin territory, and I'm willing to make the attempt at one, if anyone has any pointers that might help.

**Comment by AsaAyers** [comment]
https://www.npmjs.com/package/coffeelint-undefined-variables

I have a plugin to do this. It isn't perfect, but it's a good start. Any contributions would be greatly appreciated. Working on that project just hasn't been a priority for me recently.

I know the plugin name says `undefined-variables` but it also detects unused variables.
