### ISSUE TITLE
Interpolated object keys give a false warning

### ISSUE THREAD

**Issue by luketheobscure** [clutchski/coffeelint#394]
Coffeescript recently (v1.9.1) fixed interpolated object keys, but coffeelint still reports `error: unexpected :`.

The following is now valid Coffeescript: `"#{ foo }": bar`

**Comment by swang** [comment]
What version of npm are you on? It looks like coffee-script inside of coffeelint doesn't update. (I was using 1.4.3)

Anyways, your code still won't work because now you will get an ` ✗ #4: Operators must be spaced properly. +.` error.

**Comment by luketheobscure** [comment]
Looks like it was an issue with the gems we were using. Ran coffeelint directly after installing with npm and it worked fine.
