### ISSUE TITLE
TravisCI build for Node 0.8 keeps failing

### ISSUE THREAD

**Issue by AsaAyers** [clutchski/coffeelint#397]
https://travis-ci.org/clutchski/coffeelint/builds/57158506

I don't think it's our fault. Need to decide if we're going to fix it or just stop running 0.8.

@swang do you have any thoughts on this? I think it may just be time to drop 0.8.

**Comment by swang** [comment]
Nothing we use should be causing this so I looked around and it's this issue: iarna/are-we-there-yet#2. Kinda annoying that they've made changes that regress things that were working perfectly fine in v0.8. I think for now we can assume as long as test pass for other versions, we can ignore this problem until it gets fixed.

My opinion is that we should support v0.8 for as long as we can. CoffeeScript is pretty old (albeit I don't know when coffeelint was deployed) and probably has a user base with a wide version range.

**Comment by swang** [comment]
node v0.8 seems to be passing now.
