### ISSUE TITLE
False positive: "Interpolation in single quoted strings is forbidden" on double quoted string

### ISSUE THREAD

**Issue by benjie** [clutchski/coffeelint#398]
Easily reproducible with `a = "\#{b}"` - the lint issue "Interpolation in single quoted strings is forbidden" is raised (despite lack of single quotes and explicitly disabling interpolation with a backslash).

For people in a similar boat a workaround is to simply move the slash to the opening brace: `a = "#\{b}"`

Great project - adopting it has already revealed a number of bugs we'd not have noticed otherwise! :)

**Comment by swang** [comment]
Curious. Did you come across this or did you really have code that escapes the interpolation?

**Comment by benjie** [comment]
It was some meta-programming code: takes SVGs as inputs and turns them into modules exporting React classes.
