### ISSUE TITLE
Line contains inconsistent identation

### ISSUE THREAD

**Issue by hawkerboy7** [clutchski/coffeelint#399]
I am trying to get sublime text cofeelint to work.
I've installed it and it does!
Now the problem I am facing is that I use tabs for indentation not spaces.

I can't get the settings to allow tabs as indentation. I'm sorry, it's probably very obvious but I am missing it... :( (I tried both "tab" and "tabs")
```json
    "no_tabs": {
        "level": "ignore"
    }
    "indentation": {
       "value": "tab",
       "value": "tabs",
        "level": "error"
    }
```

Ohh and I have a coffeelint.json in my project.
Changing no_trailing_whitespace to ignore (as a test) work and stops showing errors so I am configuring the right file.
```json
"no_trailing_whitespace": {
    "level": "ignore"
}
```

**Comment by AsaAyers** [comment]
Try a value of 1. You're indenting by 1 character

**Comment by hawkerboy7** [comment]
Great that worked thanks!
