### ISSUE TITLE
Block regex with flags triggers unnecessary double quotes

### ISSUE THREAD

**Issue by royaldark** [clutchski/coffeelint#405]
In #286 and #340, a bug was fixed where block regexes with interpolation incorrectly triggered the `no_unnecessary_double_quotes` rule. However, the fix does not seem to work if that block regex has any flags on it.

This passes linting, as expected:
`///#{2 + 2}///`

This throws "Unnecessary double quotes are forbidden":
`///#{2 + 2}///g`

**Comment by AsaAyers** [comment]
I think I see the problem, but I'm not quite sure what the fix is yet.

    b = ///#{"x"}[0-9]///g
    b = RegExp("x" + "[0-9]", "g");

The first parameter for `RegExp` is correctly ignoring the double quotes, but we aren't ignoring the 2nd parameter `"g"`

cc @swang

**Comment by lydell** [comment]
I suggest looking for the REGEX_START and REGEX_END tokens. (That requires CoffeeScript 1.9.1 or later I think.)

**Comment by swang** [comment]
I can see I'm a bit late to the party... haha
