### ISSUE TITLE
Bower support?

### ISSUE THREAD

**Issue by benjiwheeler** [clutchski/coffeelint#410]
Am I right in understanding that there is no way to use coffeelint in the browser if I'm only using Bower?

(I'm using a Rails backend with Angular, using Bower for JS dependencies; trying to coffeelint the code inside CodeMirror editor!)

When I try, the various references within coffeelint js files to each other don't resolve...

**Comment by AsaAyers** [comment]
CoffeeLint does run in the browser. If Bower is simply downloading from github you're going to need to find another solution, we don't commit compiled code in the repo.

You need to either define `window.CoffeeScript` before you load `coffeelint.js` or make sure that `require('coffee-script')` resolves if you're using something like Browserify. [source](https://github.com/clutchski/coffeelint/blob/master/src/coffeelint.coffee#L17-L28)

http://www.coffeelint.org/ includes a place at the top of the page to try out coffeelint. See [trycoffee.js](https://github.com/clutchski/coffeelint/blob/gh-pages/js/trycoffeelint.js)

**Comment by AsaAyers** [comment]
oh, I misread this as "Browser support". Yes we support running CoffeeLint in the browser, no I don't care to support Bower. If it's simple to do and doesn't involve committing compiled code you can submit a PR.

**Comment by benjiwheeler** [comment]
Thanks! If I npm install coffeelint, and define window.CoffeeScript, and include the resulting coffeelint.js, it should work, right? I've been getting an error message that require ./ruleLoader.js is failing, and I just have no idea where I'm going wrong :)

**Comment by AsaAyers** [comment]
oh, `ruleLoader.js` is ... special. There isn't really a way to load custom rules from the config when run from the browser. We wrap [ruleLoader](https://github.com/clutchski/coffeelint/blob/master/src/coffeelint.coffee#L204-L206) in a try/catch and try to just ignore it if it fails. ruleLoader should just fail silently and move on.

**Comment by AsaAyers** [comment]
that `nodeRequire` is a mechanism of hiding things from browserify, so that when we compile this code `ruleLoader.js` doesn't get included but will execute the native `require` of whatever environment you're in (Node, browserify, webpack?)

**Comment by benjiwheeler** [comment]
sorry, I guess I'm just not up to speed on the different contexts that js can be executed in!

I appreciate your help and patience!

when I npm install coffeelint, it's cake'ing the whole thing using browserify etc, right? but then is there anything more for browserify to be doing once the resulting code is included in a web page? it's not like that coffeelint.org page is including browserify, right?

i'm just not clear on what i might be doing differently than the coffeelint.org page.

**Comment by AsaAyers** [comment]
> it's cake'ing the whole thing using browserify etc, right?

This actually happens before I publish it to npm, so when you npm install you get a built version where everything is (nearly) self contained. Browserify analyzed the code and every require statement it can process has been packaged into the same file. So for example with `require('./rules.coffee');` we know that `rules.coffee` is handled by the very thing runtime provided by Browserify.

Now the complicated part... I intentionally hid `ruleLoader.js` from browserify so it won't package it. When we try to require a module that Browserify doesn't know about it falls back to whatever module loader exists outside of Browserify. in Node it falls back to node's ordinary `require()` to see if it can load the module. If `window.require` exists it's going to end up calling that and you're never going to have `ruleLoader.js`. This shouldn't be a problem because the error is supposed to be consumed and ignored. `ruleLoader.js` is an optional component that is only needed when run from inside Node

**Comment by AsaAyers** [comment]
I also wrote a site that uses CodeMirror with CoffeeLint. http://asaayers.github.io/clfiddle/. I wanted it to be something similar to http://jsfiddle.net/ so that when people reported CoffeeLint bugs they could link a page with their sample code /w a running version of CoffeeLint using the exact configuration they wanted. I probably spent a couple days on it but haven't come back to it in a while. Maybe the code will help you.

**Comment by benjiwheeler** [comment]
Thanks, your info about how nodeRequire/require works helped me track it down!

Looks like another js library I was using was polluting the global namespace by defining a "require" function. (the library is called Streamline, it's an asynchronous js library.)

when i omit that, the linting works!

i'll look into what it would take to make coffeelint work with bower -- i think it would not be much trouble. if i can figure it out, i'll make a PR.

thanks!!!

**Comment by benjiwheeler** [comment]
are there any files besides the coffeelint.js that the browser must find and load? to use custom rules files, do you need to use coffeelint from the commandline, or manually compile coffeelint.js? or can you use them from the browser?

**Comment by AsaAyers** [comment]
All of the built in rules are packaged in coffeelint.js. If you want to attempt to use 3rd party rules it's entirely up to you to decide how you want to load them, then register them with a call to `coffeelint.registerRule`

**Comment by benjiwheeler** [comment]
does the same go for the .json config files? the docs and commandline.coffee comments give me impression that coffeelint.json is not used in browser?

**Comment by AsaAyers** [comment]
Correct, the only thing you get in the browser is the core library `coffeelint.js`. It's up to you to provide everything else.

**Comment by benjiwheeler** [comment]
Thanks for your help. Looks like (as you suggested at the start of this issue) there's no way to compile the code, a la npm install, with bower install.

**Comment by AsaAyers** [comment]
I have a large project (for work) that used to use npm to manage the build tools and all the front end dependencies were managed with Bower. I ran into enough trouble that I decided its better to just use npm for everything. IDK if bower added it, but at the time you couldn't shrinkwrap your dependencies. One library we depended on did a patch release and completely broke our build.

Are you working on something that is or will be public?

**Comment by benjiwheeler** [comment]
yes, a learning-to-code app for kids, using an adapted form of coffeescript! example of what you can make:

![screen shot 2015-04-28 at 5 07 33 pm](https://cloud.githubusercontent.com/assets/3431616/7400898/1c47f98a-ee8e-11e4-956b-02e19b780cf1.png)

**Comment by benjiwheeler** [comment]
:) so you can make little interactive games.

**Comment by benjiwheeler** [comment]
by shrinkwrap dependencies do you mean handle recursive version dependency requirements, so you can effectively constrain the libraries so they don't update past certain points? it does that now, uses the same semver logic as node.

**Comment by benjiwheeler** [comment]
eg you could use this bower.json for coffeelint, **except** that it wouldn't have the compiled coffeelint.js to provide the browser:

{
  "name": "coffeelint",
  "description": "Lint your CoffeeScript",
  "version": "1.9.4",
  "homepage": "http://www.coffeelint.org",
  "keywords": [
    "lint",
    "coffeescript",
    "coffee-script"
  ],
  "authors": [
    "Matthew Perpick <clutchski@gmail.com>"
  ],
  "main": "./lib/coffeelint.js",
  "repository": {
    "type": "git",
    "url": "git://github.com/clutchski/coffeelint.git"
  },
  "dependencies": {
    "coffee-script": "^1.9.1"
  },
  "devDependencies": {
  },
  "license": [
      "http://github.com/clutchski/coffeelint/raw/master/LICENSE"
  ],
  "ignore": [
    "*.js",
    "*.sh",
    "*coffeelint.json",
    ".*",
    "3rd_party_rules.md",
    "Cakefile",
    "bin",
    "doc",
    "lib/cache.js",
    "lib/commandline.js",
    "lib/configfinder.js",
    "lib/reporters",
    "lib/ruleloader.js",
    "node_modules",
    "package.json",
    "src",
    "test"
  ]
}

**Comment by benjiwheeler** [comment]
i guess package.json and bower.json should get the author/authors entries updated! (the name and syntax of a few fields differs between package.json and bower.json)
