### ISSUE TITLE
TypeError: Cannot read property 'value' of undefined for MissingFatArrows rule

### ISSUE THREAD

**Issue by dracupid** [clutchski/coffeelint#412]
When I am trying to use coffeelint@1.9.6 to lint followeing code with option` "missing_fat_arrows": {"level": "error"}`
```
do -> 1
```

This throws:
```
TypeError: Cannot read property 'value' of undefined
  at MissingFatArrows.module.exports.MissingFatArrows.isConstructor
```
It seems that this bug was introduced by fixing #408.

**Comment by Zolmeister** [comment]
Yup, thanks for fixing this

**Comment by Zolmeister** [comment]
cc @AsaAyers

**Comment by Zolmeister** [comment]
woah, just realized that the reference was not a PR

**Comment by dracupid** [comment]
thx~
