### ISSUE TITLE
Create ScopeLinter

### ISSUE THREAD

**Issue by AsaAyers** [clutchski/coffeelint#415]
When I created [coffeelint-undefined-variables](https://www.npmjs.com/package/coffeelint-undefined-variables) due to poor design, I ended up mixing the "undefined variables" and "unused variables" rules together. A few weeks ago I started over on that idea and tonight I have published the first bits of code.

I created a new project ([coffeescope](https://www.npmjs.com/package/coffeescope)) that scans a file and produces nested scopes listing all variables and references. With that information available I'm now creating a `ScopeLinter` so we can have different scope related rules.

Right now the CoffeeLint branch [scope-linter](https://github.com/clutchski/coffeelint/compare/scope-linter) is just a stub. There are no rules yet, but i added the linter without breaking tests.

Once I get this all done and have the `undefined_variables` and `unused_variables` rules implemented I'll deprecate [coffeelint-undefined-variables](https://www.npmjs.com/package/coffeelint-undefined-variables)

**Comment by katspaugh** [comment]
Wonderful news!

**Comment by hccampos** [comment]
This is awesome news! It is one of the biggest things that was missing in Coffeelint.

**Comment by growlsworth** [comment]
Looking forward to this! Thanks!

**Comment by AsaAyers** [comment]
The [scope-linter](https://github.com/clutchski/coffeelint/compare/scope-linter) branch just got two new rules `no_undefined_vars` and `no_unused_vars`. If anyone is interested in helping out you can run the branch and contribute over at [CoffeeScope](https://github.com/AsaAyers/coffeescope).

Here are some of the errors I'll be working on next, as they show up when running coffeelint against itself:

False Positives
===========

CoffeeScope isn't finding where these are defined even though they are:

      ✗ src/rules/ensure_comprehensions.coffee
         ⚡ #18: Unused variable. idents.
         ✗ #24: Undefined variable. prevToken.

CoffeeScope isn't finding where these are used even though they are:

      ⚡ src/rules/no_tabs.coffee
         ⚡ #18: Unused variable. indentation.

Crash
=====

CoffeeScope simply can't scan some of the files. It wont' crash CoffeeLint but none of the scope rules will run against the file when it can't be scanned.

      ⚡ src/ast_linter.coffee
         ⚡ #1: CoffeeScope Error: Cannot call method 'unwrapAll' of null.

**Comment by mitar** [comment]
Just a comment here: in our code style we prefer having all function/callback arguments always written fully out, even if not used. But unused variables declared in function scope should be detected. So consider adding a switch which would allow unused function arguments.

**Comment by AsaAyers** [comment]
yup, got it. I even works just like http://eslint.org/docs/rules/no-unused-vars

I actually have the [rules written](https://github.com/clutchski/coffeelint/compare/scope-linter) but I haven't merged it because [CoffeeScope](https://github.com/AsaAyers/coffeescope) still misses variables and references all over the place. It gets a bunch of false positives just trying to lint coffeelint's source right now.

Does anyone here have a large coffeescript codebase I could try these rules out on when they're done? I don't know a better way to make sure it works than to just run it against as much code as I can get my hands on. I've been adding samples of false positives to the test suite so I can know when they're all fixed.

**Comment by mitar** [comment]
You can try https://github.com/peerlibrary/peerlibrary :-)

**Comment by katspaugh** [comment]
Also Atom's code: https://github.com/atom/atom/tree/master/src

**Comment by growlsworth** [comment]
@mitar, that's a great distinction. We like to be explicit in all of the function parameters as well.

**Comment by giladgray** [comment]
:+1:

**Comment by brunocoelho** [comment]
:+1:

**Comment by AsaAyers** [comment]
From CoffeeScope:

> CoffeeScript's AST doesn't have all of the information needed to determine how variables are used. The simplest example is implicit returns, they are simply missing from the AST. My workaround was to have the AST compile itself because for some dumbass reason compiling the AST allows it to modify itself and it puts in the explicit return. This introduces new problems; now the AST contains code you didn't write. Your default parameter now exists as part of the parameter AND inside an if statement in the body. This is a major problem when trying to lint what the user wrote.
> 
> I expect I am probably going to abandon this project.

If anyone wants to pick up the project and continue it you're welcome to, but my plan is to just move to using ES6 /w Babel for all new code. CoffeeScript was good for a while, but now there's no need for it.

**Comment by mitar** [comment]
Which project are we talking about here now? CoffeeScope or CoffeeLint?

**Comment by AsaAyers** [comment]
Mostly coffeescope. Without a complete list of variable declarations and references per scope you can't actually locate undefined and unused variables. 

I don't really see any other big things that coffeelint needs. I'll continue to be here to manage it.

**Comment by mitar** [comment]
> I don't really see any other big things that coffeelint needs. I'll continue to be here to manage it. 

Great! :-)

**Comment by mwager** [comment]
sad :( is there really no tool for doing unused variable detection in coffeescript? the only thing I know is webstorm..

**Comment by za-creature** [comment]
I've made some efforts towards improving the situation: https://github.com/za-creature/coffeescope

While I've started using it successfully for my own code, there are many subtleties to coffeescript that the project in its current form is probably missing. Please try it out and report any bugs or missing features.
