### ISSUE TITLE
Erroneus "Spaces are required after commas" error with ///

### ISSUE THREAD

**Issue by mitar** [clutchski/coffeelint#420]
I have `spacing_after_comma` enabled and for the following line:

```coffee
///^#{ inputValue }///i.test field.name
```

I get the following error:

```
Spaces are required after commas. ,.
```

No idea why is that happening.

**Comment by AsaAyers** [comment]
We rely on CoffeeScript to convert the source into tokens and then we read that. The code above converts to this code: `RegExp("^" + inputValue, "i").test(field.name);`

I suspect the `,` that CoffeeScript produced isn't marked as `token.spaced = true`
