### ISSUE TITLE
_ prefix for UpperCamelCased classes should not be an error

### ISSUE THREAD

**Issue by mitar** [clutchski/coffeelint#422]
When enabled UpperCamelCased class names having a class name prefixed with `_` (for private names) should not be an error.

**Comment by AsaAyers** [comment]
I've never considered prefixing a class name. This should be pretty simple to put a PR together for.

**Comment by AsaAyers** [comment]
This one is in `camel_case_classes'

https://github.com/clutchski/coffeelint/blob/master/src/rules/camel_case_classes.coffee
