### ISSUE TITLE
A rule to require one to always use @ instead of this

### ISSUE THREAD

**Issue by mitar** [clutchski/coffeelint#429]
A feature request.

A rule to require one to always use `@` instead of `this`.

**Comment by AsaAyers** [comment]
You seem to have many requests for new rules. To me they seem overly strict. Are you willing to start building and maintaining these new rules? I try to get bugs dealt with quickly, but I generally leave new rules to whoever is going to use them.

**Comment by mitar** [comment]
Yea, I will try to look into how to make them. But probably I will need some help initially. :-)

**Comment by AsaAyers** [comment]
:+1: I'll definitely help answer questions. You can probably also find many similar rules to get started. The "Building Custom Rules" on coffeelint.org has an overview of what's available. Core and 3rd party rules all have the same API access.

I thought I wrote some documentation somewhere with some guidelines on each linter type, but I can't find it. It obviously isn't helping anyone :(

**Comment by mitar** [comment]
OK, can you then go through tickets and tell me what would be good names for the rules? So what you think I should name them? If you have any preferences.

**Comment by AsaAyers** [comment]
I'd probably name this one `no_this`.

I think it's conceptually very similar to the rule about preferring `is` over `==` but its named `prefer_english_operator` and I think doesn't totally fit.
