### ISSUE TITLE
--trim-config

### ISSUE THREAD

**Issue by AsaAyers** [clutchski/coffeelint#452]
Many people use `coffeelint --makeconfig` and commit that, but it's very hard to tell how that project's config actually differs from the defaults, if it does at all. `--trim-config` should read the local configuration and diff it with the default and then output just the parts that are different.

I also don't think people are aware that you don't need to save the whole config. https://gist.github.com/AsaAyers/c58e78104ccc0d5969b5 These two configurations are exactly the same. If anyone watching has suggestions on how to make this more clear I would really appreciate it.

**Comment by aseemk** [comment]
I like this idea.
