### ISSUE TITLE
Dual-pass linting

### ISSUE THREAD

**Issue by mitar** [clutchski/coffeelint#455]
This rule [is really useful](https://github.com/alexkalderimis/coffeelint-ensure-super). But it seems it would need two passes. First to see which classes all inherit from which classes in whole codebase. And then another pass to check the code. Currently there is nothing like that available, no?

**Comment by AsaAyers** [comment]
I think that level of analysis is just too far outside the scope of CoffeeLint. I'm sure that code works by just assuming that every `View` is `Backbone.View` and that you'll never assign Backbone's view to a different variable.

```CoffeeScript
# I'm sure it can't catch this
{ View: BBView } = Backbone
class extends BBView
   remove: -> undefined
```

It would be extremely difficult to figure this set of files out through static analysis.

```CoffeeScript
# base.coffee
module.exports = class Foo
    foo: ->

Foo::bar = ->
```

```CoffeeScript
# child.coffee
Whatever = require('./base.coffee')

module.exports = class extends Whatever
  foo ->
  bar: ->
```

**Comment by mitar** [comment]
I do not think this is so complicated? Just following filenames and what they export?

So why do not provide a way to get access to all files if interested, and then let the plugin figure out the rest?

**Comment by AsaAyers** [comment]
You don't always have access to the filenames. Editors often pass the source through, sometimes source that hasn't been saved to disk yet. CoffeeLint also runs in a browser, you can't go asking for external files from there.

**Comment by AsaAyers** [comment]
One of the few rules I was given when I took over maintenance of this project was "Don't break the ability to run in the browser"

**Comment by mitar** [comment]
Yea, in that case "all files" would be only that one file. But this is like saying, because we do not yet provide an API, nobody is using it, but because nobody is using it, we do not have to provide an API. Editors could pass all files, existing or in memory, in browsers you could specify additional files as well as blobs. Like all files are these, but lint this one.

**Comment by AsaAyers** [comment]
IMO if you need that level of protection you need to use a type system. http://flowtype.org/ and http://www.typescriptlang.org/ look pretty nice. Obviously they don't work with CoffeeScript though.

**Comment by mitar** [comment]
Yea, I like that ability as well. I do not see how that would broke it though. It wouldn't prevent  anything?
