### ISSUE TITLE
node_modules/changelog forgot in package

### ISSUE THREAD

**Issue by bucatzel** [clutchski/coffeelint#463]
Somehow, the changelog package got abbandoned in the package here http://registry.npmjs.org/coffeelint/-/coffeelint-1.10.0.tgz

as it can be seen below

$ npm install coffeelint
coffeelint@1.10.0 node_modules/coffeelint
├── strip-json-comments@1.0.2
├── ignore@2.2.15
├── resolve@0.6.3
├── coffee-script@1.9.3
├── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)
└── glob@4.5.3 (inherits@2.0.1, once@1.3.2, inflight@1.0.4, minimatch@2.0.8)

$ npm ls
└─┬ coffeelint@1.10.0
  ├── changelog@1.0.7 **extraneous**
  ├── coffee-script@1.9.3
  ├─┬ glob@4.5.3
  │ ├─┬ inflight@1.0.4
  │ │ └── wrappy@1.0.1
  │ ├── inherits@2.0.1
  │ ├─┬ minimatch@2.0.8
  │ │ └─┬ brace-expansion@1.1.0
  │ │   ├── balanced-match@0.2.0
  │ │   └── concat-map@0.0.1
  │ └─┬ once@1.3.2
  │   └── wrappy@1.0.1
  ├── ignore@2.2.15
  ├─┬ optimist@0.6.1
  │ ├── minimist@0.0.10
  │ └── wordwrap@0.0.3
  ├── resolve@0.6.3
  └── strip-json-comments@1.0.2

unfortunaltely this makes npm shrinkwrap yell.
npm 2.9.0
Also tested on a machine that still had npm 1.4.3, worked like a charm, although that doesn't help my situation too much

**Comment by AsaAyers** [comment]
I'm not sure how this is possible since CoffeeLint doesn't use shrinkwrap and doesn't depend on `changelog`. I don't doubt you have a problem, I just don't know how I can help

**Comment by AsaAyers** [comment]
https://github.com/clutchski/coffeelint/compare/v1.9.7...v1.10.0

^ The diff here shows that package.json hasn't changed in a way that would do this

**Comment by charlierudolph** [comment]
When downloading http://registry.npmjs.org/coffeelint/-/coffeelint-1.10.0.tgz it already has a `node_modules` folder with a `changelog` in it.

This was probably just a bug with publishing. 

Can you please try just releasing another version? (no change to the code needed)

**Comment by AsaAyers** [comment]
http://registry.npmjs.org/coffeelint/-/coffeelint-1.10.1.tgz does *not* have a `node_modules`. I have no idea how or why npm published it on `1.10.0`

**Comment by AsaAyers** [comment]
Thanks for the help :)

**Comment by charlierudolph** [comment]
Thank you!

**Comment by bucatzel** [comment]
Thank you!
