### ISSUE TITLE
Apply line length rule prior to applying transforms

### ISSUE THREAD

**Issue by dlants** [clutchski/coffeelint#473]
The transforms (especially with coffee-react-transform) works fantastically, except for one thing - it is pretty easy for rather short lines of JSX to become long lines of coffeescript (especially since they are set up to preserve line numbers).

I wonder if it would be possible to apply the line-length rule to the code prior to pushing it through the transforms?

**Comment by AsaAyers** [comment]
No, I'm not going to add the needed complexity to make some rules run before a transform and some after. Before the transform happens you don't technically have a valid file, so CoffeeLint can't parse it.

https://github.com/clutchski/coffeelint/blob/master/doc/user.md#how-do-i-use-jsx-reactjs

> *WARNING*: CoffeeLint cannot control what these transformers do. They may
violate all kinds of rules you have setup. It's up to you to wrap your code in
`# coffeelint: disable=max_line_length` or whatever you need.

**Comment by AsaAyers** [comment]
I recommend if you're using JSX, switch to ES6 with [Babel](http://babeljs.io/). I believe it has far better tools than CoffeeScript will ever have.
