### ISSUE TITLE
coffeelint --version still reports 1.9.3

### ISSUE THREAD

**Issue by cueedee** [clutchski/coffeelint#477]
According to the package.json I do have version `1.10.1` installed. Yet `coffeelint --version` yields `1.9.3`

**Comment by AsaAyers** [comment]
I can't reproduce the issue. Can you provide more details?

Are you talking about the `package.json` in your project, or the one in `node_modules/coffeelint/package.json`? I'm not sure what other details I need.

**Comment by cueedee** [comment]
I apologize. I haven't figured out what is going on, but it must be my local system that is to blame, somehow...

 Depending on the terminal window used I get different results for the exact same command:
```bash
/usr/local/bin/coffeelint --version
```
In the one it's `1.9.4`, in the other it's the `1.10.1` that I was expecting to see. The two terminal sessions are on the same system, just in different directories.

**Comment by cueedee** [comment]
... 
And as it turns out, in one session the current working directory happens to be that of a project that has a non-global install of `coffeelint`, which, surely by no coincidence, happens to be version `1.9.4`.

How can it be that whilst explicitly invoking the global version, the local one gets run instead?

At least, I suspect that that must be what is happening here but it sure is freaking me out.

**Comment by AsaAyers** [comment]
The file that executes when you run `coffeelint` is very small. It's only purpose is to find and execute a version of `lib/commandline.js`. If you're in a project that has a local coffeelint then it uses `./node_modules/coffeelint/lib/commandline.js`, otherwise it uses the one that it ships with.

Lines [29 and 30](https://github.com/clutchski/coffeelint/blob/master/bin/coffeelint#L29-L30) look for a local version to use.

**Comment by cueedee** [comment]
Thanks for the enlightenment. Understanding the mechanics makes the behaviour a lot less scary, albeit counterintuitive (still). Perhaps it could be documented?

**Comment by AsaAyers** [comment]
It definitely could be. I recommend opening a pull request to add it to
wherever you would have looked. The website is in the gh-pages branch and
there is a docs folder.

**Comment by cueedee** [comment]
Thanks. I'll look into it. But it may take a while...

**Comment by AsaAyers** [comment]
That's totally fine. With the current site design I'm not sure where to put this info that people will find it. If the struggle is explaining with it I'll definitely help with that.

Even though it's unusual my hope is that it's simply doing the right thing. If your project is setup to use `1.9.3` on your CI server, then I'm sure that's the version you should be running when you lint your code while you're working. It handles upgrades too, so maybe you have `1.9.3` globally, but your project/CI is setup for `1.10.1`. In that case you don't get mysterious errors where your CI server complains about something but you can't get coffeelint to error locally.
