### ISSUE TITLE
Maintain copy of the changelog here (or link to it)

### ISSUE THREAD

**Issue by kevinburkeshyp** [clutchski/coffeelint#479]
Was trying to upgrade and figure out what changed between our current release and this one.

**Comment by AsaAyers** [comment]
http://www.coffeelint.org/#changelog

I give a summary of the important changes and the dates are a link to github where you can see every commit between the two tags.

**Comment by kevinburkeshyp** [comment]
The first place I looked (works across all Git projects in all langages) was here: https://github.com/clutchski/coffeelint/compare/v1.8.0...v1.10.0#diff-a6a747c33a0a7a5802e3587295fe5c73

Didn't see anything in the README, in a file called HISTORY or CHANGES, or an updated link to a changelog anywhere.

**Comment by AsaAyers** [comment]
If you still want something changed I recommend a PR instead of an issue
