### ISSUE TITLE
Installation requires Browserify module

### ISSUE THREAD

**Issue by paulmenzel** [clutchski/coffeelint#503]
[gulp-coffeelint](https://github.com/janraasch/gulp-coffeelint) 0.4.0 is used, which depends on CoffeeLint.

With CoffeeLint 1.11.1 everything builds fine, but now that 1.12.0 is released, `npm install` in my project fails, as it requires [Browserify](http://browserify.org) as the error output below shows.

```
> coffeelint@1.12.0 install /home/app/node_modules/gulp-coffeelint/node_modules/coffeelint
> cake install


module.js:340
    throw err;
          ^
Error: Cannot find module 'browserify'
  at Function.Module._resolveFilename (module.js:338:15)
  at Function.Module._load (module.js:280:25)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/home/app/node_modules/gulp-coffeelint/node_modules/coffeelint/Cakefile:10:16)
  at Object.<anonymous> (/home/app/node_modules/gulp-coffeelint/node_modules/coffeelint/Cakefile:90:4)
  at Module._compile (module.js:456:26)
```

It looks like this is similar to issue #385.

**Comment by AsaAyers** [comment]
@swang the problem here is that [`prepublish`](https://github.com/clutchski/coffeelint/blob/master/package.json#L44) didn't run. I have no idea why npm just doesn't bother to run it sometimes. I just got in the habit of running `npm run prepublish` before `npm publish`.

**Comment by AsaAyers** [comment]
https://github.com/clutchski/coffeelint/issues/385#issuecomment-75477031

> Sorry for causing trouble. I just don't have a better solution yet that satisfies:
> 
> * Must be able to install from GIT
> * Must be able to install from npm
> * Must NOT ship browserify/coffeeify when installing pre-compiled from npm

**Comment by swang** [comment]
OK I just pushed 1.12.1, hopefully that should fix this.

**Comment by paulmenzel** [comment]
@AsaAyers, @swang: Thank you very much for the quick responses and the release of 1.12.1!
