### ISSUE TITLE
no_unnecessary_fat_arrows: function contains super

### ISSUE THREAD

**Issue by charlierudolph** [clutchski/coffeelint#505]
If you have a function which uses `super`, the fat arrow is necessary but the rule tells you to remove it.

**Comment by swang** [comment]
Can you explain with some code? I am assuming you are writing inside an instance function (otherwise CS would complain) and AFAIK you don't need fat arrows to call `super` .

**Comment by charlierudolph** [comment]
```
class A extends B
  method: ->
    asyncFn ->
      super() 
```

method gets compiled to

```
A.prototype.method = function() {
    return asyncFn(function() {
      return A.__super__.method.call(this);
    });
  };
```

Since this is used, looks like the fat arrow is needed

**Comment by swang** [comment]
Yeah seems like a bug. I'm guessing if super is called somewhere you need to make sure fat arrows are propagated back up to the main func. I'm not intimately familiar with this rule/code so it may take me some time to find a solution. PRs accepted.

**Comment by AsaAyers** [comment]
It might be worth filing an issue in coffeescript to see if this is really the intended behavior. I can't see how that code could ever turn out well without fat arrows

**Comment by charlierudolph** [comment]
Sorry this is already supported. A team member must have been using an out of date coffeelint

**Comment by swang** [comment]
:+1: Relatedly there is an issue about this in jashkenas/coffee-script#1606
