### ISSUE TITLE
Are the changelog and npm (and github?) out of sync?

### ISSUE THREAD

**Issue by cueedee** [clutchski/coffeelint#508]
Npm tells me coffeelint's latest version is @ 1.12.1, yet [the changelog](http://www.coffeelint.org/#changelog) ends at 1.11.0. Coincidentally, there's no tag/release for this version in github either.

**Comment by swang** [comment]
I've updated the tags on GitHub. I'll also update the changelog when I get a chance.

**Comment by cueedee** [comment]
thank you!

**Comment by swang** [comment]
Change log has been updated.
