### ISSUE TITLE
newlines_after_classes still have issues

### ISSUE THREAD

**Issue by VictorHagsand** [clutchski/coffeelint#509]
After updating to latest version 1.12 i still have issues with newlines_after_classes.
The following code gives me error:
```
ItemModel = class extends Backbone.Model
    urlRoot: ->
        workspaceModel.url() + '/items'
    
itemModels = {} 
```

"Wrong count of newlines between a class and other code  Expected 1 got 2 "

**Comment by adamhadani** [comment]
:+1:  can reproduce on computer, very strange as we have other people who aren't encountering it..
