### ISSUE TITLE
Empty catch blocks trigger indentation errors for version > 1.11.1

### ISSUE THREAD

**Issue by akshat1** [clutchski/coffeelint#511]
An empty catch block (with or without comments) causes coffeelint to complain about inconsistent indentation.

Sample code
```
try
  console.log 'a tisket'
  console.log 'a tasket'
catch err
  # We'll eat the exception

console.log 'All done'
```

coffeelint@1.11.1 finds no errors with this code. However, later version (1.12.0, 1.12.1) both give the following error

```
$ coffeelint sample.coffee 
  ✗ sample.coffee
     ✗ #4: Line contains inconsistent indentation. Expected 2 got 0.

✗ Lint! » 1 error and 0 warnings in 1 file
```

**Comment by akshat1** [comment]
Thanks for the fix Shuan Wang :) :+1:

**Comment by swang** [comment]
no prob. I just release v1.13.0 with all the fixes.

**Comment by AsaAyers** [comment]
Please [update the changelog](https://github.com/clutchski/coffeelint/blob/master/doc/release.md) too.
