### ISSUE TITLE
cyclomatic_complexity

### ISSUE THREAD

**Issue by charlierudolph** [clutchski/coffeelint#530]
I would like to be able to configure this rule to only lint individual functions and not aggregate the complexity of nested functions.

```coffee
# Currently the cyclomatic complexity of x includes the cyclomatic complexity of y
# I would like a configuration to remove this 
x = ->
  #... 
  y = ->
  #...
```

Run into this in a few places.

* mocha tests
```coffee
describe 'object', ->
  beforeEach ->
  describe 'method1', ->
  describe 'method2', ->
```
* cucumber steps
```coffee
module.exports = ->
   @Given /a step/, ->
   @Then /a result/, -> 
```
* angular controller
```coffee
controller = ($scope) ->
  $scope.onSave = ->
  $scope.onClear = ->

module.exports = controller
```

Happy to implement if it would be accepted.

**Comment by swang** [comment]
Sure. That sounds like the proper way for `cyclomatic_complexity` to be handled. I can't really think of a reason why nested functions should be counted against the main function.
