### ISSUE TITLE
The checkstyle reporter is broken owing to commit 5b726f2

### ISSUE THREAD

**Issue by barrkel** [clutchski/coffeelint#537]
This change broke the checkstyle reporter because it changes an interpolated string from double quotes to single quotes:

https://github.com/clutchski/coffeelint/commit/5b726f21ebdc25dd0beba3860e8132bc5df5160f#diff-808fefa32f5a357a638247a2372ec0dd

**Comment by swang** [comment]
Thanks, I just published 1.14.2 to fix this. Will write out some tests to deal with reporters
