### ISSUE TITLE
Is it possible to send messages from TokenLinter to LineLinter?

### ISSUE THREAD

**Issue by Foolyou** [clutchski/coffeelint#539]
I find it's useful to collect some information when running TokenLinter and then pass it to LineLinter.

Or just get information of the linting file(like file path) from `tokenApi` and `lineApi`?

The rule class will be instantiate 4 times while linting a file rather than instantiate it once and then run `lintToken`, `lintLine` by sequence, so it's difficult to pass messages via the rule class. 

Also, if I pass messages via the rule module, it's difficult to distinguish informations from different files.

===

PS:
I'm making a comment linter, which checks if single-line comment follows `code here # xxx` style.

While coffee-script lexer doesn't give us any message about single-line comment, I have to check '#' in LineLinter(rather than TokenLinter). But it's painful that I need to check if '#' appears in a comment, a string or a regex, so I decided to get ranges of those tokens and then check if '#' is in those ranges.

**Comment by swang** [comment]
There's no way to pass between TokenLinter/LineLinter of a class. But In TokenLinter you can access the lines from `tokenApi.lines` (tokenApi is the second param passed to lintToken) in a TokenLinter or using `lineApi.tokensByLine` in a LineLinter.

**Comment by Foolyou** [comment]
Thanks for your reply.

`lineApi.tokensByLine` is very helpful in this case. We are going to use this API to replace our more complex way.
