### ISSUE TITLE
"Unused variable. " warning false positives

### ISSUE THREAD

**Issue by a7madgamal** [clutchski/coffeelint#544]
some coffeescript valid syntax triggers wrong "Unused variable. " warnings
example

`var1 = 1
var2 = 2
var3 = 3
cond = 2
test = switch cond
  when var1 then 'bar'
  when var2 then 'far'
  when var3 then 'car'
  else 'nar'`

although var1,var2 and var3 are used in the code they are reported unused!
same for `  isSafeEnv: (env) ->
    env in ['development', 'testing']`
env is reported unused!

**Comment by AsaAyers** [comment]
CoffeeLint doesn't have an "Unused variable" rule. In my own research I found that CoffeeScript just doesn't provide a way to make that rule reliable. Someone else may have published a rule that claims to spot unused variables, you need to open this issue there.
