### ISSUE TITLE
Exactly one space around equality signs

### ISSUE THREAD

**Issue by hpurmann** [clutchski/coffeelint#548]
From https://github.com/clutchski/coffeelint/issues/71, which is closed and thus apparently not looked at anymore

> Is there any option to enforce having exactly one space around equality signs? To prevent people from aligning the equality signs of subsequent lines with additional spaces.

From my company's style guide:
- Do not use more than one space around these operators
```coffeescript
# Yes
x = 1
y = 1
fooBar = 3

# No
x      = 1
y      = 1
fooBar = 3
```
Which would be nice to enforce by a coffeelint rule.

**Comment by AsaAyers** [comment]
It seems like `space_operators` should handle this. If it doesn't, then I recommend a pull request. To maintain compatibility the rule will need to opt into stricter enforcement of the spacing.

I saw your comment, but I have moved on from CoffeeScript to ES6. I'm not investing any significant time into a project for a dying language. People can even write [3rd party rules](https://www.npmjs.com/search?q=coffeelintrule) so there is rarely a need to do anything in this project at this point.
