### ISSUE TITLE
no_unnecessary_double_quotes, shouldn't apply to "\n"

### ISSUE THREAD

**Issue by GaryKing** [clutchski/coffeelint#569]
`no_unnecessary_double_quotes` shouldn't apply to `"\n"`, such as in `text.split("\n")`.

The above code triggers when `no_unnecessary_double_quotes` is enabled, but it shouldn't. Same goes for `"\r"` I imagine.

**Comment by swang** [comment]
I'm not sure why it shouldn't apply? Both single quotes and double quotes are string literals in javascript so '\n' is read in as a newline by javascript.

**Comment by GaryKing** [comment]
Hm interesting, I guess I picked this up from somewhere else. I guess you're right!
