### ISSUE TITLE
Add IDEA plugin at list of existing CoffeeeLint plugin

### ISSUE THREAD

**Issue by MattMattV** [clutchski/coffeelint#575]
Just discovered CoffeeLint and naturally searched for an IDEA plugin (PHPStorm in my case) and found this : https://github.com/idok/coffee-lint-plugin

I thought you may want to know it to add it to the web page 😉

**Comment by AsaAyers** [comment]
Go ahead and open a pull request

**Comment by AsaAyers** [comment]
Does this also mean you recently discovered CoffeeScript? If so, I highly recommend you checkout Babel and learn the new JavaScript standards instead. CoffeeScript appears to have no future as it provides only 3 useful features that aren't part of JavaScript and most mistakes I've seen stem from the fact that so much of the language is implicit.

Useful Features:
* Block Regular Expressions
* existential operator for consuming nulls (`foo?.bar?.baz`)
* chained comparisons (`healthy = 200 > cholesterol > 60` vs `healthy = 200 > cholesterol && cholesterol > 60`)
