### ISSUE TITLE
"\n" is detected in the no_unnecessary_double_quotes rule.

### ISSUE THREAD

**Issue by potato4d** [clutchski/coffeelint#599]
I found an bug.
That error is detected in the no_unnecessary_double_quotes rule even though "\ n" is a necessary escape.
Here is a sample source code.

## Sample code 
https://gist.github.com/potato4d/0f58a3cb1d2e3ac6ac9a20fa4d39347c

**Comment by swang** [comment]
Hi. Thanks for submitting this issue.

There is no need issue as you don't need to use double quotes to print a control character in javascript.

**Comment by potato4d** [comment]
Oh, OK.
sry
