### ISSUE TITLE
Version 1.16.1 doesn't exist on npm

### ISSUE THREAD

**Issue by 4ver** [clutchski/coffeelint#608]

**Comment by swang** [comment]
i had to unpublish 1.16.1 because there was a regression... are you having an issue?

**Comment by szeck87** [comment]
greenkeeper bot created PRs to update all repos that depend on coffeelint to 1.16.1. Had to manually revert back to 1.16.0

**Comment by swang** [comment]
The version after this one was `2.0.0`, I republished a `1.16.2` that's just the same as `1.16.0` just in case.
