### ISSUE TITLE
Import/export supports

### ISSUE THREAD

**Issue by hufyhang** [clutchski/coffeelint#609]
Hi there,

Since 1.11.0, Coffeescript started to support `import/export` syntax. However, when I was trying to apply CoffeeLint in my company's project, it complained "Reserved keyword 'import'...".

I'm wondering if there is any chance for the import/export syntax to be supported by CoffeeLint?

Thx.

**Comment by boris-petrov** [comment]
That's strange, we're using import and export syntax and CoffeeLint doesn't complain. Are you sure your setup is correct (using the correct version of CoffeeScript everywhere e.g.)?

**Comment by hufyhang** [comment]
Problem solved.

It turns out my global coffeelint is still at a dated version (1.14.0 or something). Once I upgraded it to the latest, problem solved.

Thx a lot!
