### ISSUE TITLE
Coffeelint hangs on file with import/export and backslash line continuation

### ISSUE THREAD

**Issue by bzalasky** [clutchski/coffeelint#615]
Take a module like this:

    import MyClassA from 'my-class-a'
    import MyClassB from 'my-class-b'
    import MyClassC from 'my-class-c'
    import MyClassD from 'my-class-d'

    export default class AnotherClass extends MyClassA MyClassB \
            MyClassC MyClassD
        myMethod: -> ...

Running `coffeelint another-class.coffee` will hang, and eat up almost all my laptop's CPU and memory. If I switch back to AMD or CommonJS, line continuation doesn't cause any issues. If I remove the line continuation, the ES module will be linted as expected.

**Comment by eugenet8k** [comment]
I guess there is a massive activity going on with [CS2](https://github.com/clutchski/coffeelint/issues/595). I wonder if you should try `coffeelint` utility from branch [cs2](https://github.com/clutchski/coffeelint/tree/cs2) which is a pull request https://github.com/clutchski/coffeelint/pull/596.

**Comment by swang** [comment]
Fixed in #617, released in v2.0.3

**Comment by bzalasky** [comment]
Awesome, thanks @swang!
