### ISSUE TITLE
Push access for new maintainers?

### ISSUE THREAD

**Issue by danielbayley** [clutchski/coffeelint#648]
@swang @clutchski There are a lot of open issues and PRs left ignored; I for one would like to be given push/release access to address some of these… I also have a [number of PRs](https://github.com/aminland/coffeelint2/pulls) to the @aminland /[_coffeelint2_ fork](https://github.com/aminland/coffeelint2) of this project. With _[eslint-plugin-coffee](https://github.com/aminland/eslint-plugin-coffee)_ we can have nice modern linting for CoffeeScript.

**Comment by UziTech** [comment]
@danielbayley I have forked it to [coffeelint/coffeelint](https://github.com/coffeelint/coffeelint) and will release new versions as [@coffeelint/cli](https://www.npmjs.com/package/@coffeelint/cli) as per @clutchski's request.

If you still want to help maintain it I could add you as a maintainer.

**Comment by danielbayley** [comment]
> @danielbayley I have forked it to coffeelint/coffeelint and will release new versions as @coffeelint/cli as per @clutchski's request.

Neat!

> If you still want to help maintain it I could add you as a maintainer.

@UziTech Definitely, count me in!
