### ISSUE TITLE
Old Dependencies & Maintenance Status, and how it impacts devs

### ISSUE THREAD

**Issue by JPeisach** [clutchski/coffeelint#652]
The latest commit was a few years ago.

Remember that packages *do* update. https://github.com/ItzSwirlz/language-nim/security/dependabot/package-lock.json/minimist/open

Coffeelint is used a lot in Atom's language packages. However some dependencies as seen above are outdated.

We don't need an code update too much as coffeelint remains essentially the same-we just need the dependencies to be updated.

**Comment by UziTech** [comment]
coffeelint development has moved to https://github.com/coffeelint/coffeelint and is released as [@coffeelint/cli](https://www.npmjs.com/package/@coffeelint/cli)

@clutchski refuses to deprecate the old version

**Comment by JPeisach** [comment]
Thanks @UziTech . Doubt Atom is even aware of this since their repos don't have Dependabot really open... I'll inform them. Thanks for your help!
