### ISSUE TITLE
Inform deprecation clearly

### ISSUE THREAD

**Issue by FelipeSharkao** [clutchski/coffeelint#657]
This package (and repo) is no Roger maintained, and yet there's no mention of it neither [coffeelint.org](http://www.coffeelint.org), this repo or NPM. In fact, coffeelint.org is the first link in a google search, second is this repo.

I suggest you guys inform explicitly about the change both in NPM and in this repo, archive this repo and redirect from coffeelint.org to coffeelint.github.io.

**Comment by clutchski** [comment]
Updated readme to note this repository is no longer used.
