### ISSUE TITLE
Cannot npm install from git URL

### ISSUE THREAD

**Issue by mhart** [clutchski/coffeelint#99]
It looks like the `bin/coffeelint` file was removed a couple of months ago which means that `npm install git://github.com/clutchski/coffeelint.git` now fails with:

```
Error: ENOENT, chmod '/path/to/node_modules/coffeelint/bin/coffeelint'
```

**Comment by dawitberhe** [comment]
hi guys please help for this error when i install CORDOVA the result is this



C:\Users\Yesus> npm update -g cordova

C:\Users\Yesus> npm install -g cordova
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "cordova"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! syscall getaddrinfo

npm ERR! network getaddrinfo ENOTFOUND host
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settin
gs.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Yesus\npm-debug.log

C:\Users\Yesus>
